arb-dir: lib/l10n/arb
output-dir: lib/l10n/gen
template-arb-file: en.arb
output-localization-file: l10n.dart
output-class: Lang
synthetic-package: false
nullable-getter: false
# untranslated-messages-file: l10n_errors.txt